### PR TITLE
Streamline, proper documentation, cleanup

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
@bradrydzewski I have applied all comments from the streamline PRs.

**Comment by tboerger** [comment]
LGTM

**Comment by donny-dont** [comment]
@tboerger add an image to secrets and examples and its good to go. Though its not sure where things should go with this one.

**Comment by tboerger** [comment]
This plugin is out of interest for most now. I will close this PR.

**Pull request closed without merging**
